name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  standard-checks:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node Version 16.8.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.8.x'

      - name: Install packages
        run: yarn install
      - name: Run ESLint
        run: yarn ci:lint
      - name: Bundle and Output
        run: yarn build
